"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode = "id" | "en" | "hi" | "zh" | "ar";

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (section: string, key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const TRANSLATIONS: Record<LanguageCode, Record<string, Record<string, string>>> = {
  id: {
    common: {
      dashboard: "Dashboard",
      inquiries: "Permintaan Buyer",
      "buyer-crm": "Data Buyer",
      shipments: "Pengiriman",
      suppliers: "Pemasok",
      commodities: "Harga Komoditas",
      "negotiation-notes": "Catatan Negosiasi",
      "doc-generator": "Dokumen AI",
      settings: "Pengaturan",
      admin: "Admin",
      logout: "Keluar",
      "login-as": "Login sebagai",
      "export-office": "Kantor Ekspor",
      calculator: "Kalkulator",
      conversion: "Konversi",
      help: "Bantuan",
      "quick-guide": "Panduan Cepat Exopilot",
      loading: "Memuat data ekspor...",
      exopilot: "Exopilot",
      save: "Simpan",
      cancel: "Batal",
      delete: "Hapus",
      edit: "Ubah",
      actions: "Aksi",
      close: "Tutup",
      success: "Berhasil",
      error: "Gagal",
      status: "Status",
      search: "Cari...",
      all: "Semua",
      date: "Tanggal",
      offlineAlert: "Koneksi terputus. Anda masuk ke Mode Demo Offline, data baru tidak akan tersimpan di cloud.",
    },
    auth: {
      welcome: "Exopilot",
      subtitle: "Export Operating System",
      desc: "Kelola bisnis ekspor kamu lebih mudah — dari inquiry buyer sampai pengiriman dan dokumen.",
      tryDemo: "Coba Demo Langsung — Tanpa Daftar",
      orText: "atau masuk dengan akun",
      signIn: "Masuk",
      register: "Daftar",
      fullName: "Nama Lengkap",
      email: "Email",
      businessName: "Nama Bisnis / Perusahaan",
      password: "Password",
      confirmPassword: "Konfirmasi Password",
      submitSignIn: "Masuk ke Exopilot",
      submitRegister: "Buat Akun Ekspor",
      processing: "Memproses...",
      agreement: "Dengan masuk, kamu menyetujui Syarat Penggunaan dan Kebijakan Privasi kami.",
      features1: "Lacak pipeline & deal buyer",
      features2: "Kelola pengiriman & dokumen",
      features3: "Buat dokumen ekspor dengan AI",
    },
    dashboard: {
      bannerTitle: "Selamat Datang di Exopilot",
      bannerDesc: "Digital operating sistem premium untuk kelola pipeline inquiry, dokumen AI, pelacakan kontainer, dan rantai pasok ekspor Anda.",
      totalInquiries: "Total Permintaan",
      activeShipments: "Pengiriman Aktif",
      pipelineValue: "Nilai Pipeline",
      suppliers: "Pemasok Sourcing",
      monthlyIncrease: "Kenaikan Bulan Ini",
      followUps: "Follow-up Hari Ini",
      commoditiesCount: "Komoditas Dipantau",
      recentInquiries: "Permintaan Buyer Terbaru",
      activeShipmentsTitle: "Pelacakan Pengiriman Aktif",
      marketPrices: "Harga Pasar Rempah",
      logNewInquiry: "Catat Inquiry Baru",
      viewAll: "Lihat Semua",
      viewDetails: "Detail",
      closedDeals: "Deal Selesai",
    },
    inquiries: {
      addInquiry: "Catat Permintaan Buyer",
      pipelineTitle: "Catat Permintaan Buyer",
      pipelineSubtitle: "Tambahkan ke pipeline ekspor kamu",
      infoBuyer: "Info Buyer",
      detailProduct: "Detail Produk",
      companyField: "Nama Perusahaan Buyer",
      countryField: "Negara Tujuan Ekspor",
      sourceField: "Sumber Kontak",
      productField: "Komoditas",
      volumeField: "Volume",
      targetPriceField: "Harga Target",
      reminderField: "Pengingat Follow-up",
      nextBtn: "Lanjut →",
      backBtn: "← Kembali",
      saveBtn: "Simpan ke Pipeline",
      saving: "Menyimpan...",
      deleteConfirm: "Hapus permintaan ini dari pipeline?",
      deleteSuccess: "Permintaan dihapus.",
      saveSuccess: "Permintaan berhasil disimpan!",
      emptyState: "Belum ada permintaan. Catat permintaan pertama Anda untuk memulai pipeline ekspor!",
    },
    buyerCrm: {
      title: "Data Buyer & Ulasan",
      subtitle: "Profil lengkap buyer, riwayat transaksi, dan ulasan langsung dari Google Form.",
      buyerName: "Nama Perusahaan",
      country: "Negara",
      transactions: "Total Transaksi",
      reviews: "Ulasan Buyer",
      addReview: "Tulis Ulasan",
      shareGoogleForm: "Bagikan Google Form ke Buyer",
      shareSuccess: "Link Google Form berhasil disalin ke clipboard! Bagikan ke buyer untuk meminta ulasan.",
      reviewsPlaceholder: "Belum ada ulasan untuk buyer ini. Bagikan Google Form Anda!",
      reviewText: "Tulis review detail...",
      rating: "Rating",
      submitReview: "Simpan Ulasan",
      averageRating: "Rata-rata Rating",
      noBuyers: "Belum ada data buyer terdaftar.",
    },
    shipments: {
      title: "Pelacakan Pengiriman Laut",
      subtitle: "Pantau kontainer ekspor, tanggal keberangkatan (ETD), kedatangan (ETA), serta dokumen kapal.",
      addShipment: "Tambah Pengiriman Baru",
      activeTab: "Dalam Perjalanan",
      completedTab: "Selesai / Tiba",
      containerNo: "No. Kontainer",
      vessel: "Nama Kapal",
      weight: "Berat Muatan",
      eta: "Estimasi Tiba (ETA)",
      etd: "Estimasi Berangkat (ETD)",
      docsChecklist: "Kelengkapan Dokumen Ekspor",
      emptyState: "Belum ada pengiriman aktif terdaftar.",
      bl: "Bill of Lading (B/L)",
      coo: "Cert of Origin (COO)",
      ci: "Comm Invoice (CI)",
      pl: "Packing List (PL)",
      addModalTitle: "Daftarkan Pengiriman Baru",
      addModalSub: "Masukkan detail bill of lading dan kontainer",
    },
    suppliers: {
      title: "Jaringan Pemasok Bahan Baku",
      subtitle: "Daftar eksklusif petani, koperasi, dan pengumpul rempah lokal berkinerja tinggi.",
      addSupplier: "Daftar Pemasok Baru",
      totalSuppliers: "Pemasok Aktif",
      capacity: "Kapasitas Pasokan",
      rating: "Skor Keandalan",
      minOrder: "Minimal Pembelian",
      supplierName: "Nama Pemasok",
      commodity: "Jenis Rempah",
      contact: "No. Telepon / Kontak",
      address: "Alamat / Lokasi",
      deleteConfirm: "Hapus pemasok ini dari jaringan Anda?",
      emptyState: "Belum ada pemasok terdaftar.",
    },
    negotiation: {
      title: "Log & Catatan Negosiasi",
      subtitle: "Simpan strategi harga, taktik tawar-menawar, dan catatan penting untuk setiap deal buyer.",
      addNote: "Buat Catatan Baru",
      tacticalLog: "Log Taktik Negosiasi",
      buyerSelect: "Pilih Buyer",
      priority: "Tingkat Penting",
      content: "Isi catatan taktik negosiasi...",
      saveNote: "Simpan Catatan",
      deleteConfirm: "Hapus catatan negosiasi ini?",
      emptyState: "Belum ada catatan negosiasi. Mulai catat taktik Anda!",
    },
    docStudio: {
      title: "Studio Dokumen AI",
      subtitle: "Buat Proforma Invoice, Quotation Sheet, dan Packing List secara instan menggunakan AI.",
      selectInquiry: "Pilih Inquiry Buyer",
      selectTemplate: "Pilih Templat Dokumen",
      instructions: "Instruksi Khusus untuk AI (opsional)",
      generateBtn: "Buat Dokumen AI",
      generating: "Membuat dokumen...",
      preview: "Pratinjau Dokumen Ekspor",
      downloadPdf: "Unduh PDF Resmi",
      placeholder: "Pilih permintaan di atas dan klik 'Buat Dokumen AI' untuk memicu kecerdasan dokumen Exopilot.",
    },
    settings: {
      title: "Pengaturan Akun & Bisnis",
      subtitle: "Perbarui profil bisnis, data kontak, dan preferensi dashboard ekspor Anda.",
      profileTitle: "Profil Bisnis",
      fullName: "Nama Lengkap Pengguna",
      email: "Alamat Email",
      businessName: "Nama Resmi Perusahaan (SME)",
      saveChanges: "Simpan Perubahan",
      theme: "Tema Dashboard",
      language: "Bahasa Dashboard",
    },
    calculator: {
      title: "Kalkulator CBM Kontainer",
      subtitle: "Hitung volume total muatan karton/karung dan kecocokannya dalam kontainer standar laut.",
      length: "Panjang (cm)",
      width: "Lebar (cm)",
      height: "Tinggi (cm)",
      qty: "Jumlah Barang (box/bag)",
      weight: "Berat per Barang (kg)",
      calculate: "Hitung Volume & Muatan",
      totalCbm: "Total Volume (CBM)",
      totalWeight: "Total Berat (Ton)",
      suitability: "Kesesuaian Kontainer",
      fit20: "Muat di 20ft Container (Maks 28 CBM)",
      fit40: "Muat di 40ft Container (Maks 58 CBM)",
      fit45: "Muat di 40ft HQ Container (Maks 68 CBM)",
    },
    converter: {
      title: "Konverter Margin Ekspor",
      subtitle: "Hitung harga FOB (Free On Board) dengan simulasi margin keuntungan dan biaya operational.",
      cost: "Biaya Bahan Baku (per kg)",
      localCost: "Biaya Domestik & Logistik (FOB)",
      margin: "Target Margin Keuntungan (%)",
      usdRate: "Kurs USD ke IDR",
      simulate: "Simulasikan Harga Jual FOB",
      fobUsd: "Rekomendasi FOB USD/kg",
      profitCbm: "Estimasi Profit per Kontainer 20ft",
      cifSim: "Simulasi CIF (Cost, Insurance & Freight)",
    },
    landing: {
      navFeatures: "Fitur",
      navHowItWorks: "Cara Kerja",
      navReviews: "Ulasan",
      navSignIn: "Masuk",
      navGetStarted: "Mulai Sekarang",
      heroBadge: "Didukung oleh Gemini AI · Dibuat untuk UKM Ekspor",
      heroTitleTemplate: "{highlight} untuk Eksportir Modern",
      heroTitleHighlight: "Sistem Operasi Ekspor",
      heroTitlePart2: "untuk Eksportir Modern",
      heroSubtitle: "Kelola permintaan buyer, lacak pengiriman, buat dokumen berbasis AI, dan kembangkan bisnis ekspor Anda — semua dari satu platform cerdas.",
      heroGetStarted: "Mulai Gratis",
      heroSignIn: "Masuk ke Dashboard",
      trustNoCard: "Tanpa kartu kredit",
      trustFreeTrial: "Uji coba gratis 30 hari",
      trustCancelAnytime: "Batal kapan saja",
      mockActiveInquiries: "Permintaan Aktif",
      mockLiveShipments: "Pengiriman Aktif",
      mockPipelineValue: "Nilai Pipeline",
      mockSuppliers: "Pemasok",
      mockRecentInquiries: "Permintaan Terbaru",
      mockMarketPrices: "Harga Pasar",
      mockCountryGermany: "🇩🇪 Jerman",
      mockCountryJapan: "🇯🇵 Jepang",
      mockCountryUae: "🇦🇪 UEA",
      mockStatusNegotiating: "Negosiasi",
      mockStatusClosed: "Deal Selesai",
      mockStatusNew: "Inquiry Baru",
      mockCommodityNutmeg: "Pala",
      mockCommodityCloves: "Cengkih",
      mockCommodityMace: "Fuli",
      testimonial1Name: "Ahmad Fauzi",
      testimonial1Role: "PT Rempah Nusantara Abadi",
      testimonial2Name: "Siti Rahayu",
      testimonial2Role: "CV Agro Mandiri Export",
      testimonial3Name: "Budi Santoso",
      testimonial3Role: "UD Spice International",
      featuresSub: "Semua Yang Anda Butuhkan",
      featuresTitle: "Dibuat khusus untuk bisnis ekspor",
      featuresDesc: "Setiap fitur dirancang sesuai dengan alur kerja nyata UKM ekspor global.",
      featInquiryTitle: "Pipeline Permintaan Buyer",
      featInquiryDesc: "Lacak setiap permintaan buyer dari kontak pertama hingga deal selesai dengan manajemen status yang cerdas.",
      featShipmentTitle: "Pelacak Pengiriman",
      featShipmentDesc: "Pantau kontainer, dokumen, dan ETA secara real-time. Jangan pernah melewatkan pengiriman lagi.",
      featDocTitle: "Studio Dokumen AI",
      featDocDesc: "Buat penawaran, invoice, dan kontrak profesional dalam hitungan detik menggunakan Gemini AI.",
      featPriceTitle: "Pemantau Harga Pasar",
      featPriceDesc: "Tetap update dengan harga komoditas. Ambil keputusan harga berbasis data dengan data pasar langsung.",
      featCrmTitle: "CRM Buyer",
      featCrmDesc: "Bangun hubungan buyer jangka panjang dengan CRM khusus yang dibuat untuk bisnis ekspor.",
      featSupplierTitle: "Jaringan Pemasok",
      featSupplierDesc: "Kelola pemasok sourcing Anda, lacak skor keandalan, dan perluas rantai pasokan Anda.",
      pillCalculator: "Kalkulator Kontainer",
      pillConverter: "Konverter Mata Uang",
      pillNotes: "Catatan Negosiasi",
      pillSecure: "Aman & Terenkripsi",
      howSub: "Pengaturan Mudah",
      howTitle: "Aktif dan berjalan dalam hitungan menit",
      step1Title: "Daftarkan bisnis ekspor Anda",
      step1Desc: "Buat akun Anda dalam kurang dari 2 menit. Tambahkan detail perusahaan Anda dan Anda siap mulai.",
      step2Title: "Catat buyer & pengiriman Anda",
      step2Desc: "Tambahkan permintaan buyer, lacak kontainer pengiriman, dan kelola jaringan pemasok Anda — semua di satu tempat.",
      step3Title: "Buat dokumen dengan AI",
      step3Desc: "Biarkan Gemini AI menyusun dokumen ekspor Anda. Unduh sebagai PDF dan kirim ke buyer Anda secara instan.",
      reviewSub: "Disukai oleh Eksportir",
      reviewTitle: "Dipercaya oleh bisnis ekspor di seluruh dunia",
      review1Text: "Exopilot benar-benar mengubah cara kami mengelola hubungan buyer. Kami beralih dari spreadsheet ke sistem profesional hanya dalam satu hari.",
      review2Text: "Generator dokumen AI menghemat waktu kami 3 jam per penawaran. Buyer kami sangat menyukai betapa profesionalnya dokumen kami sekarang.",
      review3Text: "Akhirnya sebuah platform yang dibuat untuk eksportir global. Dukungan multi-bahasa dan pelacak pengiriman adalah fitur yang luar biasa.",
      ctaTitle: "Siap mengembangkan bisnis ekspor Anda?",
      ctaDesc: "Bergabunglah dengan ratusan eksportir global yang telah menggunakan Exopilot untuk mengelola bisnis mereka dengan lebih cerdas.",
      ctaGetStarted: "Mulai Secara Gratis",
      ctaAlreadyAccount: "Sudah punya akun?",
      footerSubtitle: "Sistem Operasi Ekspor untuk UKM Global",
      footerBuiltBy: "Dibuat dengan ❤️ oleh Praisilia",
      statExporters: "Eksportir Aktif",
      statPipeline: "Pipeline Dilacak",
      statDocs: "Dokumen Dibuat",
      statSatisfaction: "Tingkat Kepuasan"
    }
  },
  en: {
    common: {
      dashboard: "Dashboard",
      inquiries: "Buyer Inquiries",
      "buyer-crm": "Buyer CRM",
      shipments: "Shipments",
      suppliers: "Suppliers",
      commodities: "Commodity Prices",
      "negotiation-notes": "Negotiation Notes",
      "doc-generator": "AI Documents",
      settings: "Settings",
      admin: "Admin",
      logout: "Logout",
      "login-as": "Logged in as",
      "export-office": "Export Office",
      calculator: "Calculator",
      conversion: "Converter",
      help: "Help",
      "quick-guide": "Exopilot Quick Guide",
      loading: "Loading export data...",
      exopilot: "Exopilot",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      actions: "Actions",
      close: "Close",
      success: "Success",
      error: "Error",
      status: "Status",
      search: "Search...",
      all: "All",
      date: "Date",
      offlineAlert: "Connection lost. You have entered Offline Demo Mode; new data will not be saved to the cloud.",
    },
    auth: {
      welcome: "Exopilot",
      subtitle: "Export Operating System",
      desc: "Manage your export business with absolute ease — from buyer inquiries to shipments and documents.",
      tryDemo: "Try Demo Instantly — No Sign Up",
      orText: "or log in with your account",
      signIn: "Sign In",
      register: "Register",
      fullName: "Full Name",
      email: "Email",
      businessName: "Business / Company Name",
      password: "Password",
      confirmPassword: "Confirm Password",
      submitSignIn: "Sign In to Exopilot",
      submitRegister: "Create Export Account",
      processing: "Processing...",
      agreement: "By signing in, you agree to our Terms of Service and Privacy Policy.",
      features1: "Track buyer pipelines & deals",
      features2: "Manage shipments & documents",
      features3: "Generate export docs with AI",
    },
    dashboard: {
      bannerTitle: "Welcome to Exopilot",
      bannerDesc: "Premium digital operating system to manage your inquiry pipeline, AI documents, container tracking, and export supply chain.",
      totalInquiries: "Total Inquiries",
      activeShipments: "Active Shipments",
      pipelineValue: "Pipeline Value",
      suppliers: "Sourcing Suppliers",
      monthlyIncrease: "Increase This Month",
      followUps: "Follow-ups Today",
      commoditiesCount: "Monitored Commodities",
      recentInquiries: "Recent Buyer Inquiries",
      activeShipmentsTitle: "Active Shipment Tracking",
      marketPrices: "Spice Market Prices",
      logNewInquiry: "Log New Inquiry",
      viewAll: "View All",
      viewDetails: "Details",
      closedDeals: "Closed Deals",
    },
    inquiries: {
      addInquiry: "Log Buyer Inquiry",
      pipelineTitle: "Log Buyer Inquiry",
      pipelineSubtitle: "Add this inquiry to your export pipeline",
      infoBuyer: "Buyer Info",
      detailProduct: "Product Details",
      companyField: "Buyer Company Name",
      countryField: "Export Destination Country",
      sourceField: "Contact Source",
      productField: "Commodity",
      volumeField: "Volume",
      targetPriceField: "Target Price",
      reminderField: "Follow-up Reminder",
      nextBtn: "Next →",
      backBtn: "← Back",
      saveBtn: "Save to Pipeline",
      saving: "Saving...",
      deleteConfirm: "Remove this inquiry from your pipeline?",
      deleteSuccess: "Inquiry removed.",
      saveSuccess: "Inquiry successfully saved!",
      emptyState: "No inquiries yet. Log your first inquiry to start your export pipeline!",
    },
    buyerCrm: {
      title: "Buyer Profiles & Reviews",
      subtitle: "Comprehensive buyer profiles, transaction history, and direct feedback from Google Form integration.",
      buyerName: "Company Name",
      country: "Country",
      transactions: "Total Transactions",
      reviews: "Buyer Reviews",
      addReview: "Write a Review",
      shareGoogleForm: "Share Google Form with Buyer",
      shareSuccess: "Google Form link copied to clipboard! Share it with the buyer to request a review.",
      reviewsPlaceholder: "No reviews for this buyer yet. Share your Google Form!",
      reviewText: "Write detailed review...",
      rating: "Rating",
      submitReview: "Save Review",
      averageRating: "Average Rating",
      noBuyers: "No buyers registered yet.",
    },
    shipments: {
      title: "Ocean Freight Shipment Tracking",
      subtitle: "Monitor export containers, estimated departure (ETD), arrival (ETA), and shipping documentation.",
      addShipment: "Register New Shipment",
      activeTab: "In Transit",
      completedTab: "Completed / Arrived",
      containerNo: "Container No.",
      vessel: "Vessel Name",
      weight: "Cargo Weight",
      eta: "Estimated Arrival (ETA)",
      etd: "Estimated Departure (ETD)",
      docsChecklist: "Export Document Checklist",
      emptyState: "No active shipments registered.",
      bl: "Bill of Lading (B/L)",
      coo: "Cert of Origin (COO)",
      ci: "Comm Invoice (CI)",
      pl: "Packing List (PL)",
      addModalTitle: "Register New Shipment",
      addModalSub: "Enter bill of lading and container details",
    },
    suppliers: {
      title: "Supply Sourcing Network",
      subtitle: "An exclusive directory of high-performance farmers, cooperatives, and local spice collectors.",
      addSupplier: "Register New Supplier",
      totalSuppliers: "Active Suppliers",
      capacity: "Sourcing Capacity",
      rating: "Reliability Score",
      minOrder: "Minimum Order Qty",
      supplierName: "Supplier Name",
      commodity: "Spice Commodity",
      contact: "Phone / Contact Info",
      address: "Address / Location",
      deleteConfirm: "Remove this supplier from your network?",
      emptyState: "No suppliers registered yet.",
    },
    negotiation: {
      title: "Negotiation Logs & Tactics",
      subtitle: "Record price strategies, counter-offers, and crucial pointers for every buyer interaction.",
      addNote: "Create New Log",
      tacticalLog: "Tactical Negotiation Feed",
      buyerSelect: "Select Buyer",
      priority: "Priority Level",
      content: "Write down negotiation tactics & logs...",
      saveNote: "Save Log",
      deleteConfirm: "Delete this negotiation log?",
      emptyState: "No negotiation logs found. Start logging your tactics!",
    },
    docStudio: {
      title: "AI Export Document Studio",
      subtitle: "Instantly draft Proforma Invoices, Quotation Sheets, and Packing Lists powered by AI.",
      selectInquiry: "Select Buyer Inquiry",
      selectTemplate: "Select Document Template",
      instructions: "Special AI Prompt/Instructions (optional)",
      generateBtn: "Generate AI Document",
      generating: "Generating document...",
      preview: "Export Document Preview",
      downloadPdf: "Download Official PDF",
      placeholder: "Select an inquiry above and click 'Generate AI Document' to trigger Exopilot's document intelligence.",
    },
    settings: {
      title: "Account & Enterprise Settings",
      subtitle: "Update your business profile, contact details, and export dashboard preferences.",
      profileTitle: "Business Profile",
      fullName: "User's Full Name",
      email: "Email Address",
      businessName: "Official Company Name (SME)",
      saveChanges: "Save Settings",
      theme: "Dashboard Theme",
      language: "Dashboard Language",
    },
    calculator: {
      title: "Container Payload & CBM Calculator",
      subtitle: "Compute total volume of your carton boxes/bags and see how they pack into standard ocean containers.",
      length: "Length (cm)",
      width: "Width (cm)",
      height: "Height (cm)",
      qty: "Quantity (boxes/bags)",
      weight: "Unit Weight (kg)",
      calculate: "Calculate Cargo Payload",
      totalCbm: "Total Cargo Volume (CBM)",
      totalWeight: "Total Gross Weight (Tons)",
      suitability: "Container Suitability",
      fit20: "Fits in 20ft Container (Max 28 CBM)",
      fit40: "Fits in 40ft Container (Max 58 CBM)",
      fit45: "Fits in 40ft HQ Container (Max 68 CBM)",
    },
    converter: {
      title: "Export Margin & FOB Simulator",
      subtitle: "Determine your Free On Board (FOB) price based on raw spice cost, domestic shipping, and target margin.",
      cost: "Raw Commodity Cost (per kg)",
      localCost: "Domestic Logistics & Port Fees",
      margin: "Target Profit Margin (%)",
      usdRate: "USD exchange rate",
      simulate: "Simulate FOB Selling Price",
      fobUsd: "Recommended FOB USD/kg",
      profitCbm: "Estimated Profit per 20ft Container",
      cifSim: "CIF Simulation (Cost, Insurance & Freight)",
    },
    landing: {
      navFeatures: "Features",
      navHowItWorks: "How It Works",
      navReviews: "Reviews",
      navSignIn: "Sign In",
      navGetStarted: "Get Started Free",
      heroBadge: "Powered by Gemini AI · Built for Export SMEs",
      heroTitleTemplate: "The {highlight} for Modern Exporters",
      heroTitleHighlight: "Export Operating System",
      heroTitlePart2: "for Modern Exporters",
      heroSubtitle: "Manage buyer inquiries, track shipments, generate AI-powered documents, and grow your export business — all from one intelligent platform.",
      heroGetStarted: "Get Started Free",
      heroSignIn: "Sign In to Dashboard",
      trustNoCard: "No credit card required",
      trustFreeTrial: "Free 30-day trial",
      trustCancelAnytime: "Cancel anytime",
      mockActiveInquiries: "Active Inquiries",
      mockLiveShipments: "Live Shipments",
      mockPipelineValue: "Pipeline Value",
      mockSuppliers: "Suppliers",
      mockRecentInquiries: "Recent Inquiries",
      mockMarketPrices: "Market Prices",
      mockCountryGermany: "🇩🇪 Germany",
      mockCountryJapan: "🇯🇵 Japan",
      mockCountryUae: "🇦🇪 UAE",
      mockStatusNegotiating: "Negotiating",
      mockStatusClosed: "Closed Deal",
      mockStatusNew: "New Inquiry",
      mockCommodityNutmeg: "Nutmeg",
      mockCommodityCloves: "Cloves",
      mockCommodityMace: "Mace",
      testimonial1Name: "Ahmad Fauzi",
      testimonial1Role: "PT Rempah Nusantara Abadi",
      testimonial2Name: "Siti Rahayu",
      testimonial2Role: "Agro Mandiri Export Co.",
      testimonial3Name: "Budi Santoso",
      testimonial3Role: "UD Spice International",
      featuresSub: "Everything You Need",
      featuresTitle: "Built specifically for export businesses",
      featuresDesc: "Every feature is designed around the real workflow of global export SMEs.",
      featInquiryTitle: "Buyer Inquiry Pipeline",
      featInquiryDesc: "Track every buyer inquiry from first contact to closed deal with smart status management.",
      featShipmentTitle: "Shipment Tracker",
      featShipmentDesc: "Monitor containers, documents, and ETAs in real-time. Never miss a delivery again.",
      featDocTitle: "AI Document Studio",
      featDocDesc: "Generate professional quotations, invoices, and contracts in seconds using Gemini AI.",
      featPriceTitle: "Market Price Tracker",
      featPriceDesc: "Stay updated on commodity prices. Make data-driven pricing decisions with live market data.",
      featCrmTitle: "Buyer CRM",
      featCrmDesc: "Build long-term buyer relationships with a dedicated CRM built for export businesses.",
      featSupplierTitle: "Supplier Network",
      featSupplierDesc: "Manage your sourcing suppliers, track reliability scores, and expand your supply chain.",
      pillCalculator: "Container Calculator",
      pillConverter: "Currency Converter",
      pillNotes: "Negotiation Notes",
      pillSecure: "Secure & Encrypted",
      howSub: "Simple Setup",
      howTitle: "Up and running in minutes",
      step1Title: "Register your export business",
      step1Desc: "Create your account in under 2 minutes. Add your company details and you're ready to go.",
      step2Title: "Log your buyers & shipments",
      step2Desc: "Add buyer inquiries, track shipment containers, and manage your supplier network — all in one place.",
      step3Title: "Generate documents with AI",
      step3Desc: "Let Gemini AI draft your export documents. Download as PDF and send to your buyers instantly.",
      reviewSub: "Loved by Exporters",
      reviewTitle: "Trusted by export businesses worldwide",
      review1Text: "Exopilot completely transformed how we manage our buyer relationships. We went from spreadsheets to a professional system in one day.",
      review2Text: "The AI document generator saves us 3 hours per quotation. Our buyers love how professional our documents look now.",
      review3Text: "Finally a platform built for global exporters. Multi-language support and the shipment tracker are game changers.",
      ctaTitle: "Ready to grow your export business?",
      ctaDesc: "Join hundreds of global exporters who already use Exopilot to manage their business smarter.",
      ctaGetStarted: "Start For Free",
      ctaAlreadyAccount: "Already have an account?",
      footerSubtitle: "Export Operating System for Global SMEs",
      footerBuiltBy: "Built with ❤️ by Praisilia",
      statExporters: "Active Exporters",
      statPipeline: "Pipeline Tracked",
      statDocs: "Documents Generated",
      statSatisfaction: "Satisfaction Rate"
    }
  },
  hi: {
    common: {
      dashboard: "डैशबोर्ड",
      inquiries: "बायर्स पूछताछ",
      "buyer-crm": "बायर सीआरएम",
      shipments: "शिपमेंट ट्रैकिंग",
      suppliers: "आपूर्तिकर्ता",
      commodities: "वस्तु कीमतें",
      "negotiation-notes": "बातचीत नोट्स",
      "doc-generator": "एआई दस्तावेज़",
      settings: "सेटिंग्स",
      admin: "प्रशासक",
      logout: "लॉग आउट",
      "login-as": "लॉग इन किया है",
      "export-office": "निर्यात कार्यालय",
      calculator: "कैलकुलेटर",
      conversion: "कनवर्टर",
      help: "सहायता",
      "quick-guide": "एक्सोपायलट त्वरित गाइड",
      loading: "निर्यात डेटा लोड हो रहा है...",
      exopilot: "एक्सोपायलट",
      save: "सहेजें",
      cancel: "रद्द करें",
      delete: "हटाएं",
      edit: "संपादित करें",
      actions: "कार्रवाई",
      close: "बंद करें",
      success: "सफलता",
      error: "त्रुटि",
      status: "स्थिति",
      search: "खोजें...",
      all: "सभी",
      date: "दिनांक",
      offlineAlert: "कनेक्शन टूट गया। आप ऑफ़लाइन डेमो मोड में प्रवेश कर चुके हैं, नया डेटा क्लाउड पर सहेजा नहीं जाएगा।",
    },
    auth: {
      welcome: "एक्सोपायलट",
      subtitle: "निर्यात ऑपरेटिंग सिस्टम",
      desc: "अपने निर्यात व्यवसाय को बहुत आसानी से प्रबंधित करें — खरीदार की पूछताछ से लेकर शिपमेंट और दस्तावेजों तक।",
      tryDemo: "सीधे डेमो आज़माएं — बिना साइन अप",
      orText: "या अपने खाते से लॉग इन करें",
      signIn: "लॉग इन",
      register: "पंजीकरण",
      fullName: "पूरा नाम",
      email: "ईमेल",
      businessName: "व्यवसाय / कंपनी का नाम",
      password: "पासवर्ड",
      confirmPassword: "पासवर्ड की पुष्टि करें",
      submitSignIn: "एक्सोपायलट में लॉग इन करें",
      submitRegister: "निर्यात खाता बनाएं",
      processing: "प्रसंस्करण हो रहा है...",
      agreement: "लॉग इन करके, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं।",
      features1: "खरीदार पाइपलाइनों और सौदों को ट्रैक करें",
      features2: "शिपमेंट और दस्तावेजों का प्रबंधन करें",
      features3: "एआई के साथ निर्यात दस्तावेज़ तैयार करें",
    },
    dashboard: {
      bannerTitle: "एक्सोपायलट में आपका स्वागत है",
      bannerDesc: "अपनी पूछताछ पाइपलाइन, एआई दस्तावेज, कंटेनर ट्रैकिंग और निर्यात आपूर्ति श्रृंखला को प्रबंधित करने के लिए प्रीमियम डिजिटल ऑपरेटिंग सिस्टम।",
      totalInquiries: "कुल पूछताछ",
      activeShipments: "सक्रिय शिपमेंट",
      pipelineValue: "पाइपलाइन मूल्य",
      suppliers: "सोर्सिंग आपूर्तिकर्ता",
      monthlyIncrease: "इस महीने की वृद्धि",
      followUps: "आज की अनुवर्ती कार्रवाई",
      commoditiesCount: "निगरानी की जा रही वस्तुएं",
      recentInquiries: "हाल ही की खरीदार पूछताछ",
      activeShipmentsTitle: "सक्रिय शिपमेंट ट्रैकिंग",
      marketPrices: "मसाला बाजार कीमतें",
      logNewInquiry: "नई पूछताछ दर्ज करें",
      viewAll: "सभी देखें",
      viewDetails: "विवरण",
      closedDeals: "बंद सौदे",
    },
    inquiries: {
      addInquiry: "खरीदार पूछताछ दर्ज करें",
      pipelineTitle: "खरीदार पूछताछ दर्ज करें",
      pipelineSubtitle: "इस पूछताछ को अपनी निर्यात पाइपलाइन में जोड़ें",
      infoBuyer: "खरीदार की जानकारी",
      detailProduct: "उत्पाद विवरण",
      companyField: "खरीदार कंपनी का नाम",
      countryField: "निर्यात गंतव्य देश",
      sourceField: "संपर्क स्रोत",
      productField: "वस्तु",
      volumeField: "मात्रा",
      targetPriceField: "लक्षित मूल्य",
      reminderField: "अनुवर्ती अनुस्मारक",
      nextBtn: "आगे →",
      backBtn: "← पीछे",
      saveBtn: "पाइपलाइन में सहेजें",
      saving: "सहेजा जा रहा है...",
      deleteConfirm: "इस पूछताछ को अपनी पाइपलाइन से हटाएं?",
      deleteSuccess: "पूछताछ हटा दी गई।",
      saveSuccess: "पूछताछ सफलतापूर्वक सहेजी गई!",
      emptyState: "अभी तक कोई पूछताछ नहीं है। अपनी निर्यात पाइपलाइन शुरू करने के लिए अपनी पहली पूछताछ दर्ज करें!",
    },
    buyerCrm: {
      title: "खरीदार प्रोफाइल और समीक्षाएं",
      subtitle: "व्यापक खरीदार प्रोफाइल, लेनदेन इतिहास, और Google फॉर्म एकीकरण से सीधे प्रतिक्रिया।",
      buyerName: "कंपनी का नाम",
      country: "देश",
      transactions: "कुल लेनदेन",
      reviews: "खरीदार समीक्षाएं",
      addReview: "एक समीक्षा लिखें",
      shareGoogleForm: "खरीदार के साथ Google फॉर्म साझा करें",
      shareSuccess: "गूगल फॉर्म लिंक क्लिपबोर्ड पर कॉपी हो गया! समीक्षा का अनुरोध करने के लिए इसे खरीदार के साथ साझा करें।",
      reviewsPlaceholder: "इस खरीदार के लिए अभी तक कोई समीक्षा नहीं है। अपना Google फ़ॉर्म साझा करें!",
      reviewText: "विस्तृत समीक्षा लिखें...",
      rating: "रेटिंग",
      submitReview: "समीक्षा सहेजें",
      averageRating: "औसत रेटिंग",
      noBuyers: "अभी तक कोई खरीदार पंजीकृत नहीं है।",
    },
    shipments: {
      title: "समुद्री माल शिपमेंट ट्रैकिंग",
      subtitle: "निर्यात कंटेनरों, अनुमानित प्रस्थान (ETD), आगमन (ETA) और शिपिंग दस्तावेजों की निगरानी करें।",
      addShipment: "नया शिपमेंट पंजीकृत करें",
      activeTab: "मार्ग में",
      completedTab: "पूर्ण / आ गया",
      containerNo: "कंटेनर नंबर",
      vessel: "जहाज का नाम",
      weight: "कार्गो वजन",
      eta: "अनुमानित आगमन (ETA)",
      etd: "अनुमानित प्रस्थान (ETD)",
      docsChecklist: "निर्यात दस्तावेज़ चेकलिस्ट",
      emptyState: "कोई सक्रिय शिपमेंट पंजीकृत नहीं है।",
      bl: "बिल ऑफ लैडिंग (B/L)",
      coo: "उत्पत्ति का प्रमाण पत्र (COO)",
      ci: "वाणिज्यिक चालान (CI)",
      pl: "पैकिंग सूची (PL)",
      addModalTitle: "नया शिपमेंट पंजीकृत करें",
      addModalSub: "बिल ऑफ लैडिंग और कंटेनर विवरण दर्ज करें",
    },
    suppliers: {
      title: "आपूर्ति सोर्सिंग नेटवर्क",
      subtitle: "उच्च प्रदर्शन करने वाले किसानों, सहकारी समितियों और स्थानीय मसाला संग्रहकर्ताओं की एक विशेष निर्देशिका।",
      addSupplier: "नया आपूर्तिकर्ता पंजीकृत करें",
      totalSuppliers: "सक्रिय आपूर्तिकर्ता",
      capacity: "सोर्सिंग क्षमता",
      rating: "विश्वसनीयता स्कोर",
      minOrder: "न्यूनतम ऑर्डर मात्रा",
      supplierName: "आपूर्तिकर्ता का नाम",
      commodity: "मसाला वस्तु",
      contact: "फोन / संपर्क जानकारी",
      address: "पता / स्थान",
      deleteConfirm: "इस आपूर्तिकर्ता को अपने नेटवर्क से हटाएं?",
      emptyState: "अभी तक कोई आपूर्तिकर्ता पंजीकृत नहीं है।",
    },
    negotiation: {
      title: "बातचीत लॉग और रणनीति",
      subtitle: "हर खरीदार बातचीत के लिए मूल्य रणनीतियों, काउंटर-ऑफ़र और महत्वपूर्ण बिंदुओं को रिकॉर्ड करें।",
      addNote: "नया लॉग बनाएं",
      tacticalLog: "सामरिक बातचीत फ़ीड",
      buyerSelect: "खरीदार चुनें",
      priority: "प्राथमिकता स्तर",
      content: "बातचीत की रणनीति और लॉग लिखें...",
      saveNote: "लॉग सहेजें",
      deleteConfirm: "इस बातचीत लॉग को हटाएं?",
      emptyState: "कोई बातचीत लॉग नहीं मिला। अपनी रणनीतियों को लॉग करना शुरू करें!",
    },
    docStudio: {
      title: "एआई निर्यात दस्तावेज़ स्टूडियो",
      subtitle: "एआई द्वारा संचालित प्रोफॉर्म इनवॉइस, कोटेशन शीट और पैकिंग लिस्ट को तुरंत ड्राफ्ट करें।",
      selectInquiry: "खरीदार पूछताछ का चयन करें",
      selectTemplate: "दस्तावेज़ टेम्पलेट चुनें",
      instructions: "विशेष एआई निर्देश (वैकल्पिक)",
      generateBtn: "एआई दस्तावेज़ उत्पन्न करें",
      generating: "दस्तावेज़ तैयार किया जा रहा है...",
      preview: "निर्यात दस्तावेज़ पूर्वावलोकन",
      downloadPdf: "आधिकारिक पीडीएफ डाउनलोड करें",
      placeholder: "एक्सोपायलट की दस्तावेज़ खुफिया जानकारी को ट्रिगर करने के लिए ऊपर एक पूछताछ का चयन करें और 'एआई दस्तावेज़ उत्पन्न करें' पर क्लिक करें।",
    },
    settings: {
      title: "खाता और उद्यम सेटिंग्स",
      subtitle: "अपना व्यवसाय प्रोफ़ाइल, संपर्क विवरण और निर्यात डैशबोर्ड प्राथमिकताएं अपडेट करें।",
      profileTitle: "व्यवसाय प्रोफ़ाइल",
      fullName: "उपयोगकर्ता का पूरा नाम",
      email: "ईमेल पता",
      businessName: "आधिकारिक कंपनी का नाम (एसएमई)",
      saveChanges: "सेटिंग्स सहेजें",
      theme: "डैशबोर्ड थीम",
      language: "डैशबोर्ड भाषा",
    },
    calculator: {
      title: "कंटेनर पेलोड और सीबीएम कैलकुलेटर",
      subtitle: "अपने कार्टन बक्से/बैग के कुल आयतन की गणना करें और देखें कि वे मानक कंटेनरों में कैसे पैक होते हैं।",
      length: "लंबाई (सेमी)",
      width: "चौड़ाई (सेमी)",
      height: "ऊंचाई (सेमी)",
      qty: "मात्रा (बक्से/बैग)",
      weight: "इकाई वजन (किग्रा)",
      calculate: "कार्गो पेलोड की गणना करें",
      totalCbm: "कुल कार्गो आयतन (CBM)",
      totalWeight: "कुल सकल वजन (टन)",
      suitability: "कंटेनर उपयुक्तता",
      fit20: "20 फीट कंटेनर में फिट बैठता है (अधिकतम 28 CBM)",
      fit40: "40 फीट कंटेनर में फिट बैठता है (अधिकतम 58 CBM)",
      fit45: "40 फीट HQ कंटेनर में फिट बैठता है (अधिकतम 68 CBM)",
    },
    converter: {
      title: "निर्यात मार्जिन और एफओबी सिम्युलेटर",
      subtitle: "कच्चे मसाले की लागत, घरेलू शिपिंग और लक्षित मार्जिन के आधार पर अपनी फ्री ऑन बोर्ड (FOB) कीमत निर्धारित करें।",
      cost: "कच्ची वस्तु की लागत (प्रति किलोग्राम)",
      localCost: "घरेलू रसद और बंदरगाह शुल्क",
      margin: "लक्षित लाभ मार्जिन (%)",
      usdRate: "यूएसडी विनिमय दर",
      simulate: "एफओबी बिक्री मूल्य का अनुकरण करें",
      fobUsd: "अनुशंसित एफओबी USD/किग्रा",
      profitCbm: "20 फीट कंटेनर के लिए अनुमानित लाभ",
      cifSim: "सीआईएफ सिमुलेशन (लागत, बीमा और माल ढुलाई)",
    },
    landing: {
      navFeatures: "विशेषताएं",
      navHowItWorks: "यह कैसे काम करता है",
      navReviews: "समीक्षाएं",
      navSignIn: "लॉग इन",
      navGetStarted: "शुरू करें",
      heroBadge: "जेमिनी एआई द्वारा संचालित · निर्यात एसएमई के लिए निर्मित",
      heroTitleTemplate: "आधुनिक निर्यातकों के लिए {highlight}",
      heroTitleHighlight: "निर्यात ऑपरेटिंग सिस्टम",
      heroTitlePart2: "आधुनिक निर्यातकों के लिए",
      heroSubtitle: "खरीदार की पूछताछ प्रबंधित करें, शिपमेंट ट्रैक करें, एआई-संचालित दस्तावेज़ तैयार करें, और अपना निर्यात व्यवसाय बढ़ाएं — सब एक ही बुद्धिमान प्लेटफॉर्म से।",
      heroGetStarted: "मुफ्त में शुरू करें",
      heroSignIn: "डैशबोर्ड में लॉग इन करें",
      trustNoCard: "किसी क्रेडिट कार्ड की आवश्यकता नहीं",
      trustFreeTrial: "30 दिन का निःशुल्क परीक्षण",
      trustCancelAnytime: "कभी भी रद्द करें",
      mockActiveInquiries: "सक्रिय पूछताछ",
      mockLiveShipments: "लाइव शिपमेंट",
      mockPipelineValue: "पाइपलाइन मूल्य",
      mockSuppliers: "आपूर्तिकर्ता",
      mockRecentInquiries: "हाल ही की पूछताछ",
      mockMarketPrices: "बाजार कीमतें",
      mockCountryGermany: "🇩🇪 जर्मनी",
      mockCountryJapan: "🇯🇵 जापान",
      mockCountryUae: "🇦🇪 यूएई",
      mockStatusNegotiating: "बातचीत",
      mockStatusClosed: "सौदा बंद",
      mockStatusNew: "नई पूछताछ",
      mockCommodityNutmeg: "जायफल",
      mockCommodityCloves: "लौंग",
      mockCommodityMace: "जावित्री",
      testimonial1Name: "अहमद फौजी",
      testimonial1Role: "पीटी रेम्पाह नुसंतारा अबादी",
      testimonial2Name: "सती रायु",
      testimonial2Role: "एग्रो मंदिरी एक्सपोर्ट",
      testimonial3Name: "बुद्धि संतोसो",
      testimonial3Role: "यूडी स्पाइस इंटरनेशनल",
      featuresSub: "हर वो चीज़ जिसकी आपको आवश्यकता है",
      featuresTitle: "विशेष रूप से निर्यात व्यवसायों के लिए निर्मित",
      featuresDesc: "हर सुविधा इंडोनेशियाई और वैश्विक निर्यात एसएमई के वास्तविक वर्कफ़्लो के इर्द-गिर्द डिज़ाइन की गई है।",
      featInquiryTitle: "खरीदार पूछताछ पाइपलाइन",
      featInquiryDesc: "स्मार्ट स्थिति प्रबंधन के साथ पहले संपर्क से लेकर बंद सौदे तक हर खरीदार की पूछताछ को ट्रैक करें।",
      featShipmentTitle: "शिपमेंट ट्रैकर",
      featShipmentDesc: "वास्तविक समय में कंटेनर, दस्तावेज़ और ईटीए की निगरानी करें। फिर कभी कोई डिलीवरी न चूकें।",
      featDocTitle: "एआई दस्तावेज़ स्टूडियो",
      featDocDesc: "जेमिनी एआई का उपयोग करके सेकंडों में पेशेवर कोटेशन, चालान और अनुबंध तैयार करें।",
      featPriceTitle: "बाजार मूल्य ट्रैकर",
      featPriceDesc: "कमोडिटी की कीमतों पर अपडेट रहें। लाइव मार्केट डेटा के साथ डेटा-संचालित मूल्य निर्धारण निर्णय लें।",
      featCrmTitle: "खरीदार सीआरएम",
      featCrmDesc: "निर्यात व्यवसायों के लिए निर्मित एक समर्पित सीआरएम के साथ खरीदार के साथ दीर्घकालिक संबंध बनाएं।",
      featSupplierTitle: "आपूर्तिकर्ता नेटवर्क",
      featSupplierDesc: "अपने सोर्सिंग आपूर्तिकर्ताओं को प्रबंधित करें, विश्वसनीयता स्कोर ट्रैक करें, और अपनी आपूर्ति श्रृंखला का विस्तार करें।",
      pillCalculator: "कंटेनर कैलकुलेटर",
      pillConverter: "मुद्रा परिवर्तक",
      pillNotes: "बातचीत नोट्स",
      pillSecure: "सुरक्षित और एन्क्रिप्टेड",
      howSub: "आसान सेटअप",
      howTitle: "मिनटों में काम शुरू करें",
      step1Title: "अपना निर्यात व्यवसाय पंजीकृत करें",
      step1Desc: "2 मिनट से भी कम समय में अपना खाता बनाएं। अपनी कंपनी का विवरण जोड़ें और आप तैयार हैं।",
      step2Title: "अपने खरीदार और शिपमेंट दर्ज करें",
      step2Desc: "खरीदार की पूछताछ जोड़ें, शिपमेंट कंटेनरों को ट्रैक करें, और अपने आपूर्तिकर्ता नेटवर्क को प्रबंधित करें — सब एक ही स्थान पर।",
      step3Title: "एआई के साथ दस्तावेज़ तैयार करें",
      step3Desc: "जेमिनी एआई को अपने निर्यात दस्तावेज़ों का मसौदा तैयार करने दें। पीडीएफ के रूप में डाउनलोड करें और तुरंत अपने खरीदारों को भेजें।",
      reviewSub: "निर्यातकों द्वारा पसंद किया गया",
      reviewTitle: "पूरे इंडोनेशिया में निर्यात व्यवसायों द्वारा विश्वसनीय",
      review1Text: "एक्सोपायलट ने खरीदार संबंधों को प्रबंधित करने के हमारे तरीके को पूरी तरह से बदल दिया। हम एक ही दिन में स्प्रेडशीट से एक पेशेवर प्रणाली पर आ गए।",
      review2Text: "एआई दस्तावेज़ जनरेटर हमारा प्रति कोटेशन 3 घंटे बचाता है। हमारे खरीदारों को पसंद है कि हमारे दस्तावेज़ अब कितने पेशेवर दिखते हैं।",
      review3Text: "आखिरकार इंडोनेशियाई निर्यातकों के लिए बनाया गया एक मंच। बहु-भाषा समर्थन और शिपमेंट ट्रैकर गेम चेंजर हैं।",
      ctaTitle: "अपना निर्यात व्यवसाय बढ़ाने के लिए तैयार हैं?",
      ctaDesc: "उन सैकड़ों इंडोनेशियाई निर्यातकों में शामिल हों जो अपने व्यवसाय को अधिक समझदारी से प्रबंधित करने के लिए पहले से ही एक्सोपायलट का उपयोग कर रहे हैं।",
      ctaGetStarted: "मुफ्त में शुरू करें",
      ctaAlreadyAccount: "पहले से ही एक खाता है?",
      footerSubtitle: "इंडोनेशियाई एसएमई के लिए निर्यात ऑपरेटिंग सिस्टम",
      footerBuiltBy: "प्रासिलिया द्वारा ❤️ के साथ निर्मित",
      statExporters: "सक्रिय निर्यातक",
      statPipeline: "ट्रैक की गई पाइपलाइन",
      statDocs: "दस्तावेज़ उत्पन्न",
      statSatisfaction: "संतुष्टि दर"
    }
  },
  zh: {
    common: {
      dashboard: "仪表板",
      inquiries: "买家询盘",
      "buyer-crm": "买家 CRM",
      shipments: "货运管理",
      suppliers: "供应商",
      commodities: "大宗商品价格",
      "negotiation-notes": "谈判记录",
      "doc-generator": "AI 文档",
      settings: "设置",
      admin: "管理员",
      logout: "退出登录",
      "login-as": "登录身份",
      "export-office": "出口办公室",
      calculator: "计算器",
      conversion: "转换器",
      help: "帮助",
      "quick-guide": "Exopilot 快速指南",
      loading: "正在加载出口数据...",
      exopilot: "Exopilot",
      save: "保存",
      cancel: "取消",
      delete: "删除",
      edit: "编辑",
      actions: "操作",
      close: "关闭",
      success: "成功",
      error: "错误",
      status: "状态",
      search: "搜索...",
      all: "全部",
      date: "日期",
      offlineAlert: "连接已断开。您已进入离线演示模式，新数据将不会保存至云端。",
    },
    auth: {
      welcome: "Exopilot",
      subtitle: "出口业务智能操作系统",
      desc: "轻松管理您的出口业务 — 从买家询盘到货运和文档。",
      tryDemo: "立即体验 Demo — 免注册",
      orText: "或使用已有账号登录",
      signIn: "登录",
      register: "注册",
      fullName: "姓名",
      email: "电子邮箱",
      businessName: "企业/公司名称",
      password: "密码",
      confirmPassword: "确认密码",
      submitSignIn: "登录 Exopilot",
      submitRegister: "创建出口账号",
      processing: "正在处理...",
      agreement: "登录即表示您同意我们的服务条款和隐私政策。",
      features1: "跟踪买家管道与交易",
      features2: "管理货运和出口单证",
      features3: "使用 AI 自动生成出口文件",
    },
    dashboard: {
      bannerTitle: "欢迎使用 Exopilot",
      bannerDesc: "高端出口业务数字化操作系统，助力管理询盘管道、AI 单证、集装箱跟踪及出口供应链。",
      totalInquiries: "总询盘数",
      activeShipments: "活动货运",
      pipelineValue: "管道价值",
      suppliers: "合作供应商",
      monthlyIncrease: "本月增长",
      followUps: "今日跟进",
      commoditiesCount: "监测商品数",
      recentInquiries: "最新买家询盘",
      activeShipmentsTitle: "活动集装箱货运跟踪",
      marketPrices: "香料市场行情",
      logNewInquiry: "记录新询盘",
      viewAll: "查看全部",
      viewDetails: "详情",
      closedDeals: "已完成交易",
    },
    inquiries: {
      addInquiry: "记录买家询盘",
      pipelineTitle: "记录买家询盘",
      pipelineSubtitle: "将此询盘添加到您的出口管道中",
      infoBuyer: "买家信息",
      detailProduct: "产品详情",
      companyField: "买家企业名称",
      countryField: "出口目的国",
      sourceField: "联系人来源",
      productField: "大宗商品",
      volumeField: "采购量",
      targetPriceField: "目标价格",
      reminderField: "跟进提醒时间",
      nextBtn: "下一步 →",
      backBtn: "← 返回",
      saveBtn: "保存至管道",
      saving: "正在保存...",
      deleteConfirm: "确定要从出口管道中删除此询盘吗？",
      deleteSuccess: "询盘已成功删除。",
      saveSuccess: "询盘已成功保存！",
      emptyState: "暂无询盘记录。记录您的第一个询盘以开启出口业务！",
    },
    buyerCrm: {
      title: "买家画像与评价",
      subtitle: "全面的买家画像、交易历史，以及来自 Google Form 集成的直接反馈。",
      buyerName: "企业名称",
      country: "国家",
      transactions: "总交易数",
      reviews: "买家评价",
      addReview: "撰写评价",
      shareGoogleForm: "与买家分享 Google 评价表单",
      shareSuccess: "Google Form 表单链接已成功复制到剪贴板！与买家分享以请求评价。",
      reviewsPlaceholder: "该买家暂无评价。快去分享您的 Google 表单吧！",
      reviewText: "撰写详细评价...",
      rating: "评分",
      submitReview: "保存评价",
      averageRating: "平均评分",
      noBuyers: "暂无已注册买家。",
    },
    shipments: {
      title: "海洋货运物流跟踪",
      subtitle: "实时监控出口集装箱、预计起运时间 (ETD)、预计抵达时间 (ETA) 及随船单证。",
      addShipment: "注册新运单",
      activeTab: "运输中",
      completedTab: "已抵达/已完成",
      containerNo: "集装箱号",
      vessel: "船名",
      weight: "货物重量",
      eta: "预计抵达时间 (ETA)",
      etd: "预计起运时间 (ETD)",
      docsChecklist: "出口单证核对清单",
      emptyState: "暂无已注册的活动货运运单。",
      bl: "提单 (B/L)",
      coo: "原产地证明书 (COO)",
      ci: "商业发票 (CI)",
      pl: "装箱单 (PL)",
      addModalTitle: "注册新运单",
      addModalSub: "输入提单与集装箱详细信息",
    },
    suppliers: {
      title: "原料采购网络",
      subtitle: "高绩效农户、合作社和本地香料收购商的专有目录。",
      addSupplier: "注册新供应商",
      totalSuppliers: "活动供应商",
      capacity: "采购容量",
      rating: "可靠性评分",
      minOrder: "最小起订量",
      supplierName: "供应商名称",
      commodity: "香料商品",
      contact: "联系电话 / 信息",
      address: "地址 / 位置",
      deleteConfirm: "确定要从您的网络中移除该供应商吗？",
      emptyState: "暂无供应商注册记录。",
    },
    negotiation: {
      title: "谈判日志与策略",
      subtitle: "记录价格策略、还盘方案以及与买家互动时的重要提醒。",
      addNote: "新建日志",
      tacticalLog: "谈判策略动态 feed",
      buyerSelect: "选择买家",
      priority: "优先级",
      content: "记录谈判策略与细节...",
      saveNote: "保存日志",
      deleteConfirm: "确定要删除该谈判日志吗？",
      emptyState: "未找到谈判日志。开始记录您的业务谈判策略吧！",
    },
    docStudio: {
      title: "AI 出口单证工作室",
      subtitle: "基于 AI 技术，一键生成形式发票 (PI)、报价单 (Quotation) 和装箱单 (PL)。",
      selectInquiry: "选择买家询盘",
      selectTemplate: "选择单证模板",
      instructions: "AI 专属提示词/指令 (可选)",
      generateBtn: "一键生成 AI 单证",
      generating: "正在生成单证文件...",
      preview: "出口单证文件预览",
      downloadPdf: "下载官方 PDF",
      placeholder: "在上方选择一个询盘，并点击'一键生成 AI 单证'即可触发 Exopilot 智能单证系统。",
    },
    settings: {
      title: "企业与账户设置",
      subtitle: "更新您的企业画像、联系人信息以及出口仪表板偏好设置。",
      profileTitle: "企业画像",
      fullName: "用户全名",
      email: "电子邮件地址",
      businessName: "官方企业名称 (SME)",
      saveChanges: "保存设置",
      theme: "仪表板主题",
      language: "仪表板语言",
    },
    calculator: {
      title: "集装箱装载容积 (CBM) 计算器",
      subtitle: "计算您的纸箱/包装袋的总容积，并查看其适合装入哪种规格的标准海洋集装箱。",
      length: "长度 (cm)",
      width: "宽度 (cm)",
      height: "高度 (cm)",
      qty: "数量 (箱/袋)",
      weight: "单重 (kg)",
      calculate: "计算货物装载参数",
      totalCbm: "货物总容积 (CBM)",
      totalWeight: "货物总毛重 (吨)",
      suitability: "集装箱匹配度",
      fit20: "可装入 20 尺普通柜 (最大 28 CBM)",
      fit40: "可装入 40 尺普通柜 (最大 58 CBM)",
      fit45: "可装入 40 尺高柜 HQ (最大 68 CBM)",
    },
    converter: {
      title: "出口利润与 FOB 估算器",
      subtitle: "根据原材料成本、国内物流及港口杂费，科学估算您的 FOB 出口美金单价与利润率。",
      cost: "香料原料成本 (元/kg)",
      localCost: "国内物流与港口杂费",
      margin: "目标利润率 (%)",
      usdRate: "美元兑人民币汇率",
      simulate: "估算 FOB 卖价",
      fobUsd: "推荐 FOB 美元单价/kg",
      profitCbm: "预计每个 20 尺集装箱利润",
      cifSim: "CIF 到岸价模拟 (成本 + 保险 + 运费)",
    },
    landing: {
      navFeatures: "功能",
      navHowItWorks: "工作原理",
      navReviews: "评价",
      navSignIn: "登录",
      navGetStarted: "免费开始使用",
      heroBadge: "搭载 Gemini AI · 专为出口中小企业打造",
      heroTitleHighlight: "出口业务智能操作系统",
      heroTitlePart2: "专为现代出口商打造",
      heroSubtitle: "管理买家询盘、跟踪货运、生成 AI 辅助单证，并助力您的出口业务增长 — 尽在这一智能平台。",
      heroGetStarted: "免费开始使用",
      heroSignIn: "登录控制台",
      trustNoCard: "无需信用卡",
      trustFreeTrial: "30天免费试用",
      trustCancelAnytime: "随时取消",
      mockActiveInquiries: "活动询盘",
      mockLiveShipments: "活动运单",
      mockPipelineValue: "管道价值",
      mockSuppliers: "供应商",
      mockRecentInquiries: "最新询盘",
      mockMarketPrices: "市场行情",
      featuresSub: "满足您的一切需求",
      featuresTitle: "专为出口企业打造",
      featuresDesc: "每个功能均围绕印尼及全球出口中小企业的真实工作流程设计。",
      featInquiryTitle: "买家询盘管道",
      featInquiryDesc: "借助智能状态管理，跟踪从首次接触到最终成交的每一笔买家询盘。",
      featShipmentTitle: "货运物流跟踪",
      featShipmentDesc: "实时监控集装箱、单证及 ETA，绝不错过任何一次交付。",
      featDocTitle: "AI 单证工作室",
      featDocDesc: "搭载 Gemini AI，数秒内即可自动生成专业的形式发票、报价单及合同。",
      featPriceTitle: "大宗商品价格监测",
      featPriceDesc: "实时掌握大宗商品价格。结合实时市场数据，做出数据驱动的定价决策。",
      featCrmTitle: "买家 CRM",
      featCrmDesc: "专为出口企业打造的 CRM 模块，助您建立长期的买家合作关系。",
      featSupplierTitle: "供应商网络",
      featSupplierDesc: "管理您的采购供应商，跟踪其可靠性评分，并扩展您的供应链。",
      pillCalculator: "集装箱计算器",
      pillConverter: "汇率转换器",
      pillNotes: "谈判记录",
      pillSecure: "安全加密",
      howSub: "极简配置",
      howTitle: "数分钟内即可上手使用",
      step1Title: "注册您的出口企业",
      step1Desc: "2分钟内即可完成账号创建。补充您的公司基本信息，即可开启出口管理。",
      step2Title: "登记您的买家与运单",
      step2Desc: "添加买家询盘、跟踪集装箱物流、管理供应商网络 — 一站式搞定。",
      step3Title: "使用 AI 自动生成单证",
      step3Desc: "让 Gemini AI 为您起草出口单证。即刻下载官方 PDF 文件并发送给您的买家。",
      reviewSub: "出口商的信赖之选",
      reviewTitle: "赢得了全印尼出口企业的深厚信赖",
      review1Text: "Exopilot 彻底改变了我们管理买家关系的方式。仅用一天时间，我们就从繁杂的表格过渡到了高度专业的系统。",
      review2Text: "AI 单证生成器为我们每份报价单节省了3个小时。现在买家对我们文件的专业度赞赏有加。",
      review3Text: "终于有了一个专为印尼出口商量身打造的平台。多语言支持和货运物流跟踪功能堪称行业标杆。",
      ctaTitle: "准备好实现您的出口业务增长了吗？",
      ctaDesc: "立即加入数百家已在使用 Exopilot 更加智慧化管理业务的印尼出口企业行列。",
      ctaGetStarted: "免费注册体验",
      ctaAlreadyAccount: "已有账号？",
      footerSubtitle: "专为印尼中小企业打造的出口业务智能操作系统",
      footerBuiltBy: "由 Praisilia 用 ❤️ 倾心打造",
      statExporters: "活跃出口商",
      statPipeline: "追踪的管道",
      statDocs: "生成的文档",
      statSatisfaction: "满意率"
    }
  },
  ar: {
    common: {
      dashboard: "لوحة القيادة",
      inquiries: "استفسارات المشترين",
      "buyer-crm": "إدارة علاقات المشترين",
      shipments: "الشحنات",
      suppliers: "الموردين",
      commodities: "أسعار السلع",
      "negotiation-notes": "ملاحظات المفاوضات",
      "doc-generator": "مستندات الذكاء الاصطناعي",
      settings: "الإعدادات",
      admin: "المشرف",
      logout: "تسجيل الخروج",
      "login-as": "مسجل كـ",
      "export-office": "مكتب التصدير",
      calculator: "الحاسبة",
      conversion: "المحول",
      help: "المساعدة",
      "quick-guide": "دليل إكسوبايلوت السريع",
      loading: "جاري تحميل بيانات التصدير...",
      exopilot: "إكسوبايلوت",
      save: "حفظ",
      cancel: "إلغاء",
      delete: "حذف",
      edit: "تعديل",
      actions: "الإجراءات",
      close: "إغلاق",
      success: "نجاح",
      error: "فشل",
      status: "الحالة",
      search: "بحث...",
      all: "الكل",
      date: "التاريخ",
      offlineAlert: "اتصال مفقود. لقد دخلت في وضع العرض التجريبي دون اتصال، لن يتم حفظ البيانات الجديدة في السحابة.",
    },
    auth: {
      welcome: "إكسوبايلوت",
      subtitle: "نظام تشغيل عمليات التصدير",
      desc: "أدر أعمال التصدير الخاصة بك بسهولة تامة — من استفسارات المشترين إلى الشحنات والمستندات.",
      tryDemo: "تجربة العرض التجريبي فوراً — بدون تسجيل",
      orText: "أو سجل الدخول بحسابك",
      signIn: "تسجيل الدخول",
      register: "تسجيل جديد",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      businessName: "اسم الشركة / العمل التجاري",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      submitSignIn: "سجل الدخول إلى إكسوبايلوت",
      submitRegister: "أنشئ حساب تصدير",
      processing: "جاري المعالجة...",
      agreement: "بالتسجيل، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا.",
      features1: "تتبع استفسارات وصفقات المشترين",
      features2: "إدارة الشحنات والمستندات الملاحية",
      features3: "إنشاء مستندات التصدير بالذكاء الاصطناعي",
    },
    dashboard: {
      bannerTitle: "مرحباً بك في إكسوبايلوت",
      bannerDesc: "نظام تشغيل رقمي متميز لإدارة خط أنابيب الاستفسارات، المستندات الذكية، تتبع الحاويات وسلاسل إمداد التصدير.",
      totalInquiries: "إجمالي الاستفسارات",
      activeShipments: "الشحنات النشطة",
      pipelineValue: "قيمة الصفقات",
      suppliers: "الموردين النشطين",
      monthlyIncrease: "الزيادة هذا الشهر",
      followUps: "متابعات اليوم",
      commoditiesCount: "السلع المراقبة",
      recentInquiries: "استفسارات المشترين الأخيرة",
      activeShipmentsTitle: "تتبع الشحنات الملاحية النشطة",
      marketPrices: "أسعار سوق التوابل",
      logNewInquiry: "سجل استفسار جديد",
      viewAll: "عرض الكل",
      viewDetails: "تفاصيل",
      closedDeals: "الصفقات المكتملة",
    },
    inquiries: {
      addInquiry: "تسجيل استفسار المشتري",
      pipelineTitle: "تسجيل استفسار المشتري",
      pipelineSubtitle: "أضف هذا الاستفسار لخط أنابيب التصدير",
      infoBuyer: "بيانات المشتري",
      detailProduct: "تفاصيل المنتج",
      companyField: "اسم شركة المشتري",
      countryField: "بلد وجهة التصدير",
      sourceField: "مصدر الاتصال",
      productField: "السلعة",
      volumeField: "حجم الطلب",
      targetPriceField: "السعر المستهدف",
      reminderField: "تاريخ التذكير بالمتابعة",
      nextBtn: "التالي ←",
      backBtn: "→ رجوع",
      saveBtn: "حفظ في خط الأنابيب",
      saving: "جاري الحفظ...",
      deleteConfirm: "هل تريد حذف هذا الاستفسار من خط أنابيب التصدير؟",
      deleteSuccess: "تم حذف الاستفسار.",
      saveSuccess: "تم حفظ الاستفسار بنجاح!",
      emptyState: "لا توجد استفسارات بعد. سجل استفسارك الأول لبدء خط أنابيب التصدير!",
    },
    buyerCrm: {
      title: "ملفات المشترين والتقييمات",
      subtitle: "ملفات شاملة للمشترين، سجل المعاملات والتقييمات المباشرة من تكامل نموذج Google.",
      buyerName: "اسم الشركة",
      country: "الدولة",
      transactions: "إجمالي المعاملات",
      reviews: "تقييمات المشترين",
      addReview: "اكتب تقييمًا",
      shareGoogleForm: "مشاركة نموذج Google للتقييم",
      shareSuccess: "تم نسخ رابط نموذج Google بنجاح! شاركه مع المشتري لطلب التقييم.",
      reviewsPlaceholder: "لا توجد تقييمات لهذا المشتري بعد. شارك نموذج Google الخاص بك!",
      reviewText: "اكتب مراجعة مفصلة...",
      rating: "التقييم",
      submitReview: "حفظ التقييم",
      averageRating: "متوسط التقييم",
      noBuyers: "لا يوجد مشترون مسجلون بعد.",
    },
    shipments: {
      title: "تتبع شحنات الشحن البحري",
      subtitle: "راقب حاويات التصدير، تاريخ المغادرة المتوقع (ETD)، الوصول المتوقع (ETA) والوثائق الملاحية.",
      addShipment: "سجل شحنة جديدة",
      activeTab: "في العبور",
      completedTab: "وصلت / مكتملة",
      containerNo: "رقم الحاوية",
      vessel: "اسم السفينة",
      weight: "وزن الحمولة",
      eta: "تاريخ الوصول المتوقع (ETA)",
      etd: "تاريخ المغادرة المتوقع (ETD)",
      docsChecklist: "قائمة مستندات التصدير",
      emptyState: "لا توجد شحنات نشطة مسجلة.",
      bl: "بوليصة الشحن (B/L)",
      coo: "شهادة المنشأ (COO)",
      ci: "الفاتورة التجارية (CI)",
      pl: "قائمة التعبئة (PL)",
      addModalTitle: "سجل شحنة جديدة",
      addModalSub: "أدخل تفاصيل بوليصة الشحن والحاوية",
    },
    suppliers: {
      title: "شبكة مصادر الإمداد",
      subtitle: "دليل حصري للمزارعين المتميزين، الجمعيات التعاونية وجامعي التوابل المحليين.",
      addSupplier: "سجل مورد جديد",
      totalSuppliers: "الموردين النشطين",
      capacity: "القدرة الاستيعابية للإمداد",
      rating: "مؤشر الموثوقية",
      minOrder: "الحد الأدنى للطلب",
      supplierName: "اسم المورد",
      commodity: "سلعة التوابل",
      contact: "رقم الهاتف / الاتصال",
      address: "العنوان / الموقع",
      deleteConfirm: "إزالة هذا المورد من شبكتك؟",
      emptyState: "لا يوجد موردون مسجلون بعد.",
    },
    negotiation: {
      title: "سجلات وتكتيكات المفاوضات",
      subtitle: "سجل استراتيجيات الأسعار، العروض المضادة والنقاط الحاسمة لكل تفاعل مع المشترين.",
      addNote: "أنشئ سجلًا جديدًا",
      tacticalLog: "تكتيكات المفاوضات النشطة",
      buyerSelect: "اختر المشتري",
      priority: "مستوى الأهمية",
      content: "اكتب تكتيكات وسجلات المفاوضات هنا...",
      saveNote: "حفظ السجل",
      deleteConfirm: "هل تريد حذف سجل المفاوضات هذا؟",
      emptyState: "لم يتم العثور على سجلات مفاوضات. ابدأ بتسجيل تكتيكاتك!",
    },
    docStudio: {
      title: "استوديو مستندات التصدير بالذكاء الاصطناعي",
      subtitle: "صغ مسودات الفواتير الأولية، ورقات الأسعار وقوائم التعبئة فوراً بالذكاء الاصطناعي.",
      selectInquiry: "اختر استفسار المشتري",
      selectTemplate: "اختر نموذج المستند",
      instructions: "تعليمات وتوجيهات خاصة للذكاء الاصطناعي (اختياري)",
      generateBtn: "إنشاء مستند ذكاء اصطناعي",
      generating: "جاري إنشاء المستند...",
      preview: "معاينة مستند التصدير",
      downloadPdf: "تحميل PDF الرسمي",
      placeholder: "اختر استفسارًا أعلاه واضغط على 'إنشاء مستند ذكاء اصطناعي' لتنشيط ذكاء المستندات في إكسوبايلوت.",
    },
    settings: {
      title: "إعدادات الحساب والمؤسسة",
      subtitle: "حدث ملف تعريف شركتك، بيانات الاتصال وتفضيلات لوحة التصدير الخاصة بك.",
      profileTitle: "ملف الشركة",
      fullName: "الاسم الكامل للمستخدم",
      email: "البريد الإلكتروني",
      businessName: "الاسم الرسمي للشركة (SME)",
      saveChanges: "حفظ الإعدادات",
      theme: "مظهر لوحة القيادة",
      language: "لغة لوحة القيادة",
    },
    calculator: {
      title: "حاسبة الحمولة وحجم الحاوية (CBM)",
      subtitle: "احسب الحجم الكلي للصناديق الكرتونية أو الأكياس الخاصة بك وتأكد من ملاءمتها للحاويات القياسية.",
      length: "الطول (سم)",
      width: "العرض (سم)",
      height: "الارتفاع (سم)",
      qty: "الكمية (صناديق/أكياس)",
      weight: "وزن الوحدة (كجم)",
      calculate: "احسب حمولة الشحنة",
      totalCbm: "الحجم الإجمالي للشحنة (CBM)",
      totalWeight: "الوزن الإجمالي القائم (طن)",
      suitability: "ملاءمة الحاوية",
      fit20: "تتسع في حاوية 20 قدم (بحد أقصى 28 CBM)",
      fit40: "تتسع في حاوية 40 قدم (بحد أقصى 58 CBM)",
      fit45: "تتسع في حاوية 40 قدم مرتفعة HQ (بحد أقصى 68 CBM)",
    },
    converter: {
      title: "محاكي الهامش وسعر FOB للتصدير",
      subtitle: "حدد سعر تسليم السفينة (FOB) بناءً على تكلفة المواد الخام، النقل المحلي والهامش المستهدف.",
      cost: "تكلفة السلعة الخام (لكل كجم)",
      localCost: "النقل المحلي ورسوم الميناء",
      margin: "هامش الربح المستهدف (%)",
      usdRate: "سعر صرف الدولار (USD)",
      simulate: "محاكاة سعر البيع FOB",
      fobUsd: "سعر FOB الموصى به دولارات/كجم",
      profitCbm: "الأرباح المقدرة لحاوية 20 قدم",
      cifSim: "محاكاة سعر CIF (التكلفة والتأمين والشحن)",
    },
    landing: {
      navFeatures: "الميزات",
      navHowItWorks: "كيف يعمل",
      navReviews: "المراجعات",
      navSignIn: "تسجيل الدخول",
      navGetStarted: "ابدأ مجاناً",
      heroBadge: "بدعم من Gemini AI · مصمم للمؤسسات الصغيرة والمتوسطة للتصدير",
      heroTitleHighlight: "نظام تشغيل عمليات التصدير",
      heroTitlePart2: "للمصدرين العصريين",
      heroSubtitle: "أدر استفسارات المشترين، وتتبع الشحنات، وأنشئ مستندات بالذكاء الاصطناعي، ونمّ أعمال التصدير الخاصة بك — كل ذلك من منصة ذكية واحدة.",
      heroGetStarted: "ابدأ مجاناً",
      heroSignIn: "الدخول إلى لوحة التحكم",
      trustNoCard: "لا حاجة لبطاقة ائتمان",
      trustFreeTrial: "فترة تجريبية مجانية لمدة 30 يومًا",
      trustCancelAnytime: "إلغاء في أي وقت",
      mockActiveInquiries: "الاستفسارات النشطة",
      mockLiveShipments: "الشحنات الحية",
      mockPipelineValue: "قيمة الصفقات",
      mockSuppliers: "الموردين",
      mockRecentInquiries: "الاستفسارات الأخيرة",
      mockMarketPrices: "أسعار السوق",
      featuresSub: "كل ما تحتاجه",
      featuresTitle: "مصمم خصيصاً لأعمال التصدير",
      featuresDesc: "صممت كل ميزة وفقاً لتدفق العمل الحقيقي للمؤسسات الصغيرة والمتوسطة للتصدير محلياً وعالمياً.",
      featInquiryTitle: "خط أنابيب استفسارات المشترين",
      featInquiryDesc: "تتبع كل استفسار للمشترين من أول اتصال حتى إغلاق الصفقة مع إدارة ذكية للحالة.",
      featShipmentTitle: "تتبع الشحنات",
      featShipmentDesc: "راقب الحاويات، المستندات، والمواعيد المتوقعة للوصول في الوقت الفعلي. لا تفوت أي شحنة بعد اليوم.",
      featDocTitle: "استوديو مستندات الذكاء الاصطناعي",
      featDocDesc: "أنشئ عروض أسعار، وفواتير، وعقود احترافية في ثوانٍ باستخدام ذكاء Gemini الاصطناعي.",
      featPriceTitle: "تتبع أسعار السوق",
      featPriceDesc: "ابق على اطلاع بأسعار السلع الأساسية. اتخذ قرارات تسعير قائمة على البيانات مع بيانات السوق المباشرة.",
      featCrmTitle: "إدارة علاقات المشترين",
      featCrmDesc: "ابنِ علاقات طويلة الأمد مع المشترين من خلال نظام إدارة علاقات مخصص لأعمال التصدير.",
      featSupplierTitle: "شبكة الموردين",
      featSupplierDesc: "أدر موردي المصادر وتتبع درجات موثوقيتهم ووسع سلسلة الإمداد الخاصة بك.",
      pillCalculator: "حاسبة الحاوية",
      pillConverter: "محول العملات",
      pillNotes: "ملاحظات المفاوضات",
      pillSecure: "آمن ومحمي",
      howSub: "إعداد بسيط",
      howTitle: "ابدأ العمل في دقائق معدودة",
      step1Title: "سجل عملك التصديري",
      step1Desc: "أنشئ حسابك في أقل من دقيقتين. أضف تفاصيل شركتك وتصبح جاهزاً للبدء.",
      step2Title: "سجل المشترين والشحنات الخاصة بك",
      step2Desc: "أضف استفسارات المشترين، وتتبع حاويات الشحن، وأدر شبكة الموردين الخاصة بك — كل ذلك في مكان واحد.",
      step3Title: "أنشئ مستنداتك بالذكاء الاصطناعي",
      step3Desc: "دع ذكاء Gemini الاصطناعي يصيغ مستندات التصدير الخاصة بك. حملها كملف PDF وأرسلها إلى مشتريك فوراً.",
      reviewSub: "محبوب من قبل المصدرين",
      reviewTitle: "موثوق به من قبل أعمال التصدير في جميع أنحاء إندونيسيا",
      review1Text: "غير إكسوبايلوت طريقة إدارتنا لعلاقات المشترين تماماً. انتقلنا من الجداول إلى نظام احترافي في يوم واحد.",
      review2Text: "يوفر لنا مولد المستندات بالذكاء الاصطناعي 3 ساعات لكل عرض سعر. يحب مشترونا المظهر الاحترافي لعملنا الآن.",
      review3Text: "أخيراً منصة مصممة خصيصاً للمصدرين الإندونيسيين. دعم اللغات المتعددة وتتبع الشحنات هو نقطة تحول حقيقية.",
      ctaTitle: "هل أنت جاهز لتنمية عملك التصديري؟",
      ctaDesc: "انضم إلى مئات المصدرين الإندونيسيين الذين يستخدمون إكسوبايلوت بالفعل لإدارة أعمالهم بذكاء أكبر.",
      ctaGetStarted: "ابدأ مجاناً",
      ctaAlreadyAccount: "هل لديك حساب بالفعل؟",
      footerSubtitle: "نظام تشغيل عمليات التصدير للمؤسسات الصغيرة والمتوسطة الإندونيسية",
      footerBuiltBy: "صُنع بـ ❤️ بواسطة Praisilia",
      statExporters: "المصدرين النشطين",
      statPipeline: "الصفقات المتعقبة",
      statDocs: "المستندات المنشأة",
      statSatisfaction: "معدل الرضا"
    }
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>("id");

  useEffect(() => {
    const savedLang = localStorage.getItem("exo_language") as LanguageCode;
    if (savedLang && ["id", "en", "hi", "zh", "ar"].includes(savedLang)) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem("exo_language", lang);
    // RTL Handling
    if (lang === "ar") {
      document.documentElement.dir = "rtl";
      document.documentElement.lang = "ar";
    } else {
      document.documentElement.dir = "ltr";
      document.documentElement.lang = lang;
    }
  };

  // Sync dir on initial load
  useEffect(() => {
    const savedLang = localStorage.getItem("exo_language") as LanguageCode;
    const currentLang = savedLang || "id";
    if (currentLang === "ar") {
      document.documentElement.dir = "rtl";
      document.documentElement.lang = "ar";
    } else {
      document.documentElement.dir = "ltr";
      document.documentElement.lang = currentLang;
    }
  }, [language]);

  const t = (section: string, key: string): string => {
    const sectionDict = TRANSLATIONS[language]?.[section];
    if (sectionDict && sectionDict[key]) {
      return sectionDict[key];
    }
    // Fallback to English if translation is missing
    const fallbackSection = TRANSLATIONS["en"]?.[section];
    if (fallbackSection && fallbackSection[key]) {
      return fallbackSection[key];
    }
    return key;
  };

  const isRtl = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
